import { Category, Gem } from "@/types/gem";

export const CATEGORIES: Category[] = [
    "Blue Sapphires",
    "Yellow Sapphires",
    "Pink Sapphires",
    "White Sapphires",
    "Spinel",
    "Garnet",
    "Star Sapphires",
    "Other Gemstones",
];

export const MOCK_GEMS: Gem[] = [
    {
        id: "1",
        name: "Royal Blue Sapphire",
        category: "Blue Sapphires",
        price: 2500,
        description: "A stunning royal blue sapphire from the mines of Ratnapura.",
        image: "/assets/home/bluesapphire.png",
        isFeatured: true,
        isNew: false,
        weight: 2.5,
        clarity: "Eye Clean",
        origin: "Sri Lanka",
    },
    {
        id: "2",
        name: "Golden Yellow Sapphire",
        category: "Yellow Sapphires",
        price: 1500,
        description: "Bright golden yellow sapphire, full of life.",
        image: "https://images.unsplash.com/photo-1599707367072-cd6ada2bc375?q=80&w=2000&auto=format&fit=crop",
        isFeatured: true,
        isNew: false,
        weight: 4.5,
        clarity: "VVS1",
        origin: "Sri Lanka",
    },
    {
        id: "3",
        name: "Vibrant Pink Sapphire",
        category: "Pink Sapphires",
        price: 2200,
        description: "Intense pink sapphire with excellent brilliance.",
        image: "https://images.unsplash.com/photo-1611085583191-a3b198a27a82?q=80&w=2000&auto=format&fit=crop",
        isFeatured: false,
        isNew: true,
        weight: 2.0,
        clarity: "Eye Clean",
        origin: "Madagascar",
    },
    {
        id: "4",
        name: "Pure White Sapphire",
        category: "White Sapphires",
        price: 1200,
        description: "Brilliant white sapphire, a perfect diamond alternative.",
        image: "https://images.unsplash.com/photo-1605100804763-247f67b3557e?q=80&w=2000&auto=format&fit=crop",
        isFeatured: false,
        isNew: false,
        weight: 1.5,
        clarity: "FL",
        origin: "Sri Lanka",
    },
    {
        id: "5",
        name: "Mahenge Spinel",
        category: "Spinel",
        price: 3500,
        description: "Vibrant pinkish-red spinel from the Mahenge mines.",
        image: "https://images.unsplash.com/photo-1551025510-7521e102287c?q=80&w=2000&auto=format&fit=crop",
        isFeatured: true,
        isNew: true,
        weight: 1.2,
        clarity: "VVS",
        origin: "Tanzania",
    },
    {
        id: "6",
        name: "Tsavorite Garnet",
        category: "Garnet",
        price: 2800,
        description: "Intense green tsavorite garnet with exceptional luster.",
        image: "https://images.unsplash.com/photo-1617043786394-f977bd12eddf?q=80&w=2000&auto=format&fit=crop",
        isFeatured: true,
        isNew: false,
        weight: 2.3,
        clarity: "Eye Clean",
        origin: "Kenya",
    },
    {
        id: "7",
        name: "Midnight Star Sapphire",
        category: "Star Sapphires",
        price: 3500,
        description: "Black star sapphire with a sharp 6-ray star.",
        image: "https://images.unsplash.com/photo-1605100804763-247f67b3557e?q=80&w=2000&auto=format&fit=crop",
        isFeatured: false,
        isNew: false,
        weight: 8.0,
        clarity: "Opaque",
        origin: "Sri Lanka",
    },
    {
        id: "8",
        name: "Rare Alexandrite",
        category: "Other Gemstones",
        price: 8000,
        description: "Color-changing alexandrite, green in daylight and red in lamp light.",
        image: "https://images.unsplash.com/photo-1599707367072-cd6ada2bc375?q=80&w=2000&auto=format&fit=crop",
        isFeatured: true,
        isNew: false,
        weight: 0.9,
        clarity: "VS",
        origin: "Russia",
    },
];
